
spring:
  application:
    name: electronic_device_shop
  profiles:
    active: ${ENV:dev}
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/electronic_device}
    username: ${DATABASE_USER:huyhn}
    password: ${DATABASE_PASSWORD:Huyhn12345@}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikari-id
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      minimum-idle: 3
      maximum-pool-size: 20
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy